[package]
name = "lesson01"
version = "0.1.0"
authors = ["Niels"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
gl = "0.6.0"